---
language: go
go:
  - 1.x
  - 1.10.x

install:
  - go get github.com/constabulary/gb/...

script:
  - gb vendor update --all
  - gb build
  - gb test

deploy:
  provider: releases
  api_key:
    secure: nk4RBnDafF0YCyXG89OHWsl1TpfN3ZaHkkBo2TyfjUhnEUwqta8FUY14XO11w1ImKLq4tCakrtYMP18OcUVOLdbJd1YwImzmUhHdJNscGYFutWlRplqOhwf9klC3vm4Qs7vPp93JDwnzciQbHpVfmYzZNJY68+UxiYRh5S0fvWdm9FtMGO+fLpwxxAXcV3N3Hqa8d5FI1004WVenTHs5jkAMDgIz/7FOZ43wGnP+tp0lJ2Uc6GAcO7+1W5Ut+EdoEKjJ7PQET98n5JIr96Rya94nhp75KSjMGjFcHbLg5N1nx1D77MTsbRbtNSivs1VV5oLv6UYB9GQ1+zu2I4g1kMQ0pytyxUtxZBN15qDPV6vcK91uWBEYznrkW0n/0x9tXelZRqTKBDocg6xHLt7i/xrySfMdH13K5BY8MKyYLVJTk9Djp3N+JWxvDGkhGoqe6BGJxEtvcdyQmQdZums9TNfEFXd16YbV61mJWJpraLq1soo6NK4HRN9sc9KbTZZpGvLexygTIDvp15So8uD7fn/hL3ft9zCz0LzFg/AXoD68YW0Z4nF9zCEB3AVf/x/bke9lFDGf8euuvPOFuumkPxrJDxAyG6b2lKL1Q5ELAE5GZlwZP/lKg8CDBnV8NpQbS13R7OWWIjO0djeGzx8bJYe0ft1GHEBTMxrsWbBCHyE=
  file: bin/clickhousedump
  on:
    repo: count0ru/clickhousedump
    tags: true
