---
language: go

go_import_path: github.com/count0ru/clickhousedump

go:
  - "1.x"
  - "1.10.x"

install:
  - go get github.com/constabulary/gb/...
  - go get github.com/golang/lint/golint

script:
  - gb build
  - gb test
